version: "3.8"

services:
  comtravo-flight-api:
    container_name: comtravo-flight-api
    env_file:
      - .env
    build:
      context: "./"
      dockerfile: ./Dockerfile
    ports:
      - "7000:5000"
